export interface StoreThemePreset {
  key: string
  name: string
  dark: boolean
  vars: Record<string, string>
}

// Temas claros: canvas = sussurro do matiz principal (quase-neutro), surface = sussurro do complementar.
// A identidade da cor aparece no CTA e no preço — um único destaque por tela.
// Temas escuros: seguem a mesma lógica de fundo neutro-escuro com acento colorido.
export const STORE_THEMES: StoreThemePreset[] = [
  // ── Neutros ────────────────────────────────────────────────────────────────
  {
    key: 'padrao',
    name: 'Padrão',
    dark: false,
    vars: {
      '--c-canvas':    '#ffffff',
      '--c-surface':   '#faf8f5',
      '--c-surface-2': '#f4f1eb',
      '--c-surface-3': '#ede8df',
      '--c-ink':       '#1c1813',
      '--c-ink-2':     '#6b5d52',
      '--c-ink-3':     '#9c8e84',
      '--c-ink-4':     '#c4b8ae',
      '--c-border':    '#e8e2d8',
      '--c-border-2':  '#d4cec5',
      '--c-cta':       '#1c1813',
      '--c-cta-2':     '#2c2620',
      '--c-cta-3':     '#3c3228',
      '--c-cta-fg':    '#ffffff',
    },
  },
  {
    key: 'neve',
    name: 'Neve',
    dark: false,
    vars: {
      '--c-canvas':    '#f0f0f0',
      '--c-surface':   '#e0e0e0',
      '--c-surface-2': '#d0d0d0',
      '--c-surface-3': '#c0c0c0',
      '--c-ink':       '#181818',
      '--c-ink-2':     '#505050',
      '--c-ink-3':     '#808080',
      '--c-ink-4':     '#a8a8a8',
      '--c-border':    '#c8c8c8',
      '--c-border-2':  '#b8b8b8',
      '--c-cta':       '#181818',
      '--c-cta-2':     '#303030',
      '--c-cta-3':     '#484848',
      '--c-cta-fg':    '#f0f0f0',
    },
  },

  // ── Temas claros: canvas quase-neutro com sussurro do matiz ────────────────
  // A cor de identidade vive no CTA. Surface = sussurro do complementar (par na roda cromática).

  // CTA: âmbar dourado · Canvas: marfim morno · Surface: branco glacial (H220)
  {
    key: 'areia',
    name: 'Areia',
    dark: false,
    vars: {
      '--c-canvas':    '#faf5e8',
      '--c-surface':   '#eef0fa',
      '--c-surface-2': '#e4e8f6',
      '--c-surface-3': '#d8e0f2',
      '--c-ink':       '#1c1400',
      '--c-ink-2':     '#5a4200',
      '--c-ink-3':     '#8a6c20',
      '--c-ink-4':     '#bca060',
      '--c-border':    '#dde0f0',
      '--c-border-2':  '#cdd0e8',
      '--c-cta':       '#8a5c00',
      '--c-cta-2':     '#a07000',
      '--c-cta-3':     '#b88400',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: cobre-pêssego · Canvas: branco morno (H22) · Surface: gelo azulado (H202)
  {
    key: 'pessego',
    name: 'Pêssego',
    dark: false,
    vars: {
      '--c-canvas':    '#faf3ee',
      '--c-surface':   '#eef4fa',
      '--c-surface-2': '#e4eef8',
      '--c-surface-3': '#d8e8f4',
      '--c-ink':       '#200a00',
      '--c-ink-2':     '#6a2800',
      '--c-ink-3':     '#9a5828',
      '--c-ink-4':     '#c08060',
      '--c-border':    '#ddeaf5',
      '--c-border-2':  '#cde0f0',
      '--c-cta':       '#b84c18',
      '--c-cta-2':     '#a03c10',
      '--c-cta-3':     '#882e08',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: âmbar intenso · Canvas: creme dourado (H40) · Surface: gelo índigo (H220)
  {
    key: 'ambar',
    name: 'Âmbar',
    dark: false,
    vars: {
      '--c-canvas':    '#f8f2e0',
      '--c-surface':   '#e8eef8',
      '--c-surface-2': '#dee6f4',
      '--c-surface-3': '#d4dcef',
      '--c-ink':       '#1a1000',
      '--c-ink-2':     '#584000',
      '--c-ink-3':     '#886c18',
      '--c-ink-4':     '#b89840',
      '--c-border':    '#e0e7f5',
      '--c-border-2':  '#d0daf0',
      '--c-cta':       '#b07800',
      '--c-cta-2':     '#986400',
      '--c-cta-3':     '#805000',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: azul-oceano · Canvas: gelo azulado (H210) · Surface: branco morno (H30)
  {
    key: 'ceu',
    name: 'Céu',
    dark: false,
    vars: {
      '--c-canvas':    '#eef4fa',
      '--c-surface':   '#faf4ee',
      '--c-surface-2': '#f6ece0',
      '--c-surface-3': '#f0e4d4',
      '--c-ink':       '#00080e',
      '--c-ink-2':     '#003060',
      '--c-ink-3':     '#305880',
      '--c-ink-4':     '#6090b0',
      '--c-border':    '#f0e6d6',
      '--c-border-2':  '#e8dcc4',
      '--c-cta':       '#1060a0',
      '--c-cta-2':     '#084e88',
      '--c-cta-3':     '#043c70',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: framboesa · Canvas: branco rosado (H350) · Surface: gelo teal (H170)
  {
    key: 'rosa',
    name: 'Rosa',
    dark: false,
    vars: {
      '--c-canvas':    '#faf0f3',
      '--c-surface':   '#eef7f5',
      '--c-surface-2': '#e4f2f0',
      '--c-surface-3': '#d8eceb',
      '--c-ink':       '#200008',
      '--c-ink-2':     '#6a1030',
      '--c-ink-3':     '#9a3858',
      '--c-ink-4':     '#c87090',
      '--c-border':    '#e0f0ee',
      '--c-border-2':  '#cee8e6',
      '--c-cta':       '#9e2040',
      '--c-cta-2':     '#861030',
      '--c-cta-3':     '#6e0820',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: verde-floresta · Canvas: branco sage (H150) · Surface: branco rosado (H330)
  {
    key: 'menta',
    name: 'Menta',
    dark: false,
    vars: {
      '--c-canvas':    '#eef7f1',
      '--c-surface':   '#f9eef3',
      '--c-surface-2': '#f4e4ec',
      '--c-surface-3': '#eedad6',
      '--c-ink':       '#001408',
      '--c-ink-2':     '#104a28',
      '--c-ink-3':     '#308050',
      '--c-ink-4':     '#60b078',
      '--c-border':    '#f0e4ec',
      '--c-border-2':  '#e8d8e4',
      '--c-cta':       '#186838',
      '--c-cta-2':     '#0e5028',
      '--c-cta-3':     '#083818',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: violeta · Canvas: branco lilás (H270) · Surface: branco lima (H90)
  {
    key: 'lavanda',
    name: 'Lavanda',
    dark: false,
    vars: {
      '--c-canvas':    '#f4f1fa',
      '--c-surface':   '#f3f8ea',
      '--c-surface-2': '#ecf4df',
      '--c-surface-3': '#e5f0d4',
      '--c-ink':       '#100820',
      '--c-ink-2':     '#3c1870',
      '--c-ink-3':     '#6840a0',
      '--c-ink-4':     '#9878c8',
      '--c-border':    '#e8f3e0',
      '--c-border-2':  '#d8eacf',
      '--c-cta':       '#5430a0',
      '--c-cta-2':     '#441e88',
      '--c-cta-3':     '#341070',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: oliva profundo · Canvas: branco oliva (H100) · Surface: branco violeta (H280)
  {
    key: 'salvia',
    name: 'Sálvia',
    dark: false,
    vars: {
      '--c-canvas':    '#f1f5ec',
      '--c-surface':   '#f3f0f9',
      '--c-surface-2': '#ece8f5',
      '--c-surface-3': '#e4dff0',
      '--c-ink':       '#101600',
      '--c-ink-2':     '#3a5010',
      '--c-ink-3':     '#6a8030',
      '--c-ink-4':     '#98b060',
      '--c-border':    '#e8e4f5',
      '--c-border-2':  '#dcd8ee',
      '--c-cta':       '#485e0c',
      '--c-cta-2':     '#384a06',
      '--c-cta-3':     '#283602',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // ── Escuros — inalterados (já seguem a lógica correta) ─────────────────────

  {
    key: 'grafite',
    name: 'Grafite',
    dark: true,
    vars: {
      '--c-canvas':    '#1c1c1c',
      '--c-surface':   '#282828',
      '--c-surface-2': '#343434',
      '--c-surface-3': '#404040',
      '--c-ink':       '#f0f0f0',
      '--c-ink-2':     '#a8a8a8',
      '--c-ink-3':     '#707070',
      '--c-ink-4':     '#484848',
      '--c-border':    '#3c3c3c',
      '--c-border-2':  '#4c4c4c',
      '--c-cta':       '#f0f0f0',
      '--c-cta-2':     '#d8d8d8',
      '--c-cta-3':     '#c0c0c0',
      '--c-cta-fg':    '#1c1c1c',
    },
  },
  {
    key: 'meia-noite',
    name: 'Meia-Noite',
    dark: true,
    vars: {
      '--c-canvas':    '#0d1117',
      '--c-surface':   '#201408',
      '--c-surface-2': '#2c1c0c',
      '--c-surface-3': '#382410',
      '--c-ink':       '#f0d8a0',
      '--c-ink-2':     '#a88048',
      '--c-ink-3':     '#705028',
      '--c-ink-4':     '#3c2808',
      '--c-border':    '#302010',
      '--c-border-2':  '#442c18',
      '--c-cta':       '#58a6ff',
      '--c-cta-2':     '#3d8fe0',
      '--c-cta-3':     '#2a78c8',
      '--c-cta-fg':    '#0d1117',
    },
  },
  {
    key: 'floresta',
    name: 'Floresta',
    dark: true,
    vars: {
      '--c-canvas':    '#0d1f10',
      '--c-surface':   '#220d1a',
      '--c-surface-2': '#2e1224',
      '--c-surface-3': '#3a172e',
      '--c-ink':       '#f0d0e8',
      '--c-ink-2':     '#c880a8',
      '--c-ink-3':     '#885070',
      '--c-ink-4':     '#542840',
      '--c-border':    '#3c1830',
      '--c-border-2':  '#4c2040',
      '--c-cta':       '#4cae5c',
      '--c-cta-2':     '#3a9848',
      '--c-cta-3':     '#2e8038',
      '--c-cta-fg':    '#0d1f10',
    },
  },
  {
    key: 'vinho',
    name: 'Vinho',
    dark: true,
    vars: {
      '--c-canvas':    '#1a0810',
      '--c-surface':   '#081a14',
      '--c-surface-2': '#0e2420',
      '--c-surface-3': '#142e2a',
      '--c-ink':       '#b8f0e0',
      '--c-ink-2':     '#68c0a8',
      '--c-ink-3':     '#388870',
      '--c-ink-4':     '#185840',
      '--c-border':    '#183028',
      '--c-border-2':  '#224038',
      '--c-cta':       '#d44468',
      '--c-cta-2':     '#bc3858',
      '--c-cta-3':     '#a42c48',
      '--c-cta-fg':    '#081a14',
    },
  },
  {
    key: 'indigo',
    name: 'Índigo',
    dark: true,
    vars: {
      '--c-canvas':    '#0e0b1c',
      '--c-surface':   '#141800',
      '--c-surface-2': '#1c2200',
      '--c-surface-3': '#242c00',
      '--c-ink':       '#d8f0a0',
      '--c-ink-2':     '#90c840',
      '--c-ink-3':     '#588018',
      '--c-ink-4':     '#304800',
      '--c-border':    '#283400',
      '--c-border-2':  '#384800',
      '--c-cta':       '#8070e0',
      '--c-cta-2':     '#6858c8',
      '--c-cta-3':     '#5048b0',
      '--c-cta-fg':    '#0e0b1c',
    },
  },
  {
    key: 'espresso',
    name: 'Espresso',
    dark: true,
    vars: {
      '--c-canvas':    '#140e08',
      '--c-surface':   '#081018',
      '--c-surface-2': '#0c1824',
      '--c-surface-3': '#102030',
      '--c-ink':       '#a0c8e0',
      '--c-ink-2':     '#5898c0',
      '--c-ink-3':     '#287098',
      '--c-ink-4':     '#0c4060',
      '--c-border':    '#182838',
      '--c-border-2':  '#223848',
      '--c-cta':       '#d4a060',
      '--c-cta-2':     '#bc8c48',
      '--c-cta-3':     '#a07830',
      '--c-cta-fg':    '#081018',
    },
  },

  // ── Vibrantes — mesma lógica: canvas quase-neutro, cor no CTA ─────────────

  // CTA: terracota queimada · Canvas: branco terracota (H15) · Surface: gelo ciano (H195)
  {
    key: 'terracota',
    name: 'Terracota',
    dark: false,
    vars: {
      '--c-canvas':    '#faf2ee',
      '--c-surface':   '#eef6f8',
      '--c-surface-2': '#e4f0f4',
      '--c-surface-3': '#d8ebf0',
      '--c-ink':       '#1c0600',
      '--c-ink-2':     '#6a2010',
      '--c-ink-3':     '#9a5030',
      '--c-ink-4':     '#c87858',
      '--c-border':    '#e0eff5',
      '--c-border-2':  '#d0e8ee',
      '--c-cta':       '#b03818',
      '--c-cta-2':     '#982808',
      '--c-cta-3':     '#801c02',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: azul-mar · Canvas: gelo marinho (H207) · Surface: branco areia (H27)
  {
    key: 'oceano',
    name: 'Oceano',
    dark: false,
    vars: {
      '--c-canvas':    '#eef5fb',
      '--c-surface':   '#faf3ea',
      '--c-surface-2': '#f6ece0',
      '--c-surface-3': '#f0e4d4',
      '--c-ink':       '#000810',
      '--c-ink-2':     '#003060',
      '--c-ink-3':     '#205888',
      '--c-ink-4':     '#5090b8',
      '--c-border':    '#f0e8da',
      '--c-border-2':  '#e8dec8',
      '--c-cta':       '#0a5898',
      '--c-cta-2':     '#084880',
      '--c-cta-3':     '#063868',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: musgo profundo · Canvas: branco musgo (H75) · Surface: branco violeta (H255)
  {
    key: 'musgo',
    name: 'Musgo',
    dark: false,
    vars: {
      '--c-canvas':    '#f1f5e8',
      '--c-surface':   '#f2eef8',
      '--c-surface-2': '#ebe6f4',
      '--c-surface-3': '#e4ddf0',
      '--c-ink':       '#0e1200',
      '--c-ink-2':     '#384800',
      '--c-ink-3':     '#607818',
      '--c-ink-4':     '#90a840',
      '--c-border':    '#e8e0f4',
      '--c-border-2':  '#dcd8ee',
      '--c-cta':       '#486400',
      '--c-cta-2':     '#384e00',
      '--c-cta-3':     '#283800',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: coral-vermelho · Canvas: branco coral (H5) · Surface: gelo ciano (H185)
  {
    key: 'coral',
    name: 'Coral',
    dark: false,
    vars: {
      '--c-canvas':    '#faf1ef',
      '--c-surface':   '#eef7f8',
      '--c-surface-2': '#e4f3f4',
      '--c-surface-3': '#d8eef0',
      '--c-ink':       '#180400',
      '--c-ink-2':     '#681810',
      '--c-ink-3':     '#9a4030',
      '--c-ink-4':     '#c87060',
      '--c-border':    '#e0f3f5',
      '--c-border-2':  '#d0ecee',
      '--c-cta':       '#bc2818',
      '--c-cta-2':     '#a41e10',
      '--c-cta-3':     '#8c1408',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: ardósia · Canvas: gelo ardósia (H210) · Surface: branco areia (H30)
  {
    key: 'ardosia',
    name: 'Ardósia',
    dark: false,
    vars: {
      '--c-canvas':    '#eff4f7',
      '--c-surface':   '#f8f2eb',
      '--c-surface-2': '#f4ebe0',
      '--c-surface-3': '#ede2d4',
      '--c-ink':       '#060c12',
      '--c-ink-2':     '#1a3850',
      '--c-ink-3':     '#406880',
      '--c-ink-4':     '#6898b0',
      '--c-border':    '#efe7d8',
      '--c-border-2':  '#e6dcc8',
      '--c-cta':       '#2a5878',
      '--c-cta-2':     '#1e4462',
      '--c-cta-3':     '#14324e',
      '--c-cta-fg':    '#ffffff',
    },
  },

  // CTA: chocolate · Canvas: branco cacau (H25) · Surface: gelo aço (H205)
  {
    key: 'chocolate',
    name: 'Chocolate',
    dark: false,
    vars: {
      '--c-canvas':    '#faf2ea',
      '--c-surface':   '#eaf4fb',
      '--c-surface-2': '#e0eef8',
      '--c-surface-3': '#d6e8f4',
      '--c-ink':       '#160800',
      '--c-ink-2':     '#5a2a00',
      '--c-ink-3':     '#8a5820',
      '--c-ink-4':     '#b88840',
      '--c-border':    '#deeef8',
      '--c-border-2':  '#d0e8f4',
      '--c-cta':       '#7a3808',
      '--c-cta-2':     '#622c04',
      '--c-cta-3':     '#4c2002',
      '--c-cta-fg':    '#ffffff',
    },
  },
]

export function findTheme(key: string | null | undefined): StoreThemePreset {
  return STORE_THEMES.find((t) => t.key === key) ?? STORE_THEMES[0]
}

export function themeToStyle(key: string | null | undefined): React.CSSProperties {
  return findTheme(key).vars as React.CSSProperties
}
